name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0' # This represents 6:15 UTC every Sunday
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:      
      - name: Output the event name
        run: echo "Event that triggered this workflow:" ${{ github.event_name }}
        
      - name: Output the current branch name
        run: echo "Current branch:" $(git rev-parse --abbrev-ref HEAD)
        
      - name: List all files
        run: ls -R
